### ISSUE TITLE
Great name, but it's a Arabic word دُعَاء

### ISSUE THREAD

**Issue by imranansari** [rudimk/dua.js#4]
https://en.m.wikipedia.org/wiki/Dua

**Comment by rudimk** [comment]
The original word, yes. Hindi happens to have borrowed a lot of Arabic and Persian words, and it seems `dua` is something Hindi borrowed and then modified the meaning of.

**Comment by rudimk** [comment]
I think I should probably update the README. Thanks!

**Comment by rudimk** [comment]
Fixed in this [commit](https://github.com/rudimk/dua.js/commit/bcf0bf33398135e1f63512afa3dce86110a4f07d).
